branch-defaults:
  default:
    environment: udagram-api-dev2
environment-defaults:
  udagram-api-dev:
    branch: null
    repository: null
global:
  application_name: udagram-api
  default_ec2_keyname: vockey
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: null
  workspace_type: Application
